## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: '$' # Main Prefix 
token: 'Nzc5Njc5MzU4MzkzNjQ3MTY0.X7kC_A.G54lqLFc8C_ajPb1msQI6A3-Na8' # Token of your bot
status: '$help' # ur bot status
## Join Support Guild: https://discord.gg/devs  ##
